package:
  name: sztwiorok-test-package
  version: "1.0.0"

source:
  git_url: https://github.com/sztwiorok/conda-test-package
  git_rev: master

build:
  number: 0
  script: build.sh

requirements:
  build:
    - nodejs=20
  run:
    - nodejs=20

about:
  home: https://github.com/sztwiorok/conda-test-package
  license: MIT
  summary: "A summary of your package"
  description: |
    Long description of buddy-tunnel.

extra:
  recipe-maintainers:
    - sztwiorok